POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNob3Nlbk9uZSIsImlkIjoiNWI2ZDYyNGE1OGUwNWIyYzQ4ODg1ODI5IiwiaWF0IjoxNTMzODk1MjgyfQ.GBcjI2qWqlpLNORWQQv0jSBh2aVORyIuIBP8ZN_bGUo

{
  "title": "First Blog",
  "author": "Anonymous",
  "url": "www.uuu.com",
  "likes": 9000
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplZGkiLCJpZCI6IjViNmQ2MjRkNThlMDViMmM0ODg4NTgyYSIsImlhdCI6MTUzMzg5OTUyMX0.DgsFE-yrUlkuJBvOJnXtQQg0Vgr3xuCW4tb4jHkxd8M

{
  "title": "Another Blog",
  "author": "Anonymous",
  "url": "www.uuu.com",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkplZGkiLCJpZCI6IjViNmQ2MjRkNThlMDViMmM0ODg4NTgyYSIsImlhdCI6MTUzMzg5NTMxNH0.RoWBNzcgGXojQMF_g1gPvUEoRS58jQnrtGapM9xawNA

{
  "title": "Commented blog",
  "author": "Someone",
  "url": "www.u3u.com",
  "likes": 77,
  "comments": ["This is another comment", "Yes is it", "...?"]
}
